# Generated by Django 5.2.3 on 2026-01-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description_short",
                    models.TextField(verbose_name="Короткое описание"),
                ),
                ("description_long", models.TextField(verbose_name="Полное описание")),
                ("lng", models.FloatField(verbose_name="Долгота")),
                ("lat", models.FloatField(verbose_name="Широта")),
            ],
        ),
    ]
