# Generated by Django 5.2.3 on 2026-02-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Картинки"
            ),
        ),
    ]
