# Generated by Django 5.2.3 on 2026-04-12 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0003_alter_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["position"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
    ]
