# Generated by Django 5.2.3 on 2026-04-12 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_image_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ["position"]},
        ),
    ]
