# Generated by Django 5.2.3 on 2026-04-19 07:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_alter_image_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(verbose_name="Полное описание"),
        ),
    ]
