# Generated by Django 5.2.3 on 2026-05-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0006_alter_place_description_long"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "ordering": ["position"],
                "verbose_name": "Фотография",
                "verbose_name_plural": "Фотографии",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "Место", "verbose_name_plural": "Места"},
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
    ]
