# Generated by Django 5.2.3 on 2026-05-03 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_alter_image_options_alter_place_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="description_long",
            new_name="long_description",
        ),
        migrations.RenameField(
            model_name="place",
            old_name="description_short",
            new_name="short_description",
        ),
    ]
