# Generated by Django 5.2.3 on 2026-05-03 09:03

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0008_rename_description_long_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="long_description",
            field=tinymce.models.HTMLField(blank=True, verbose_name="Полное описание"),
        ),
        migrations.AlterField(
            model_name="place",
            name="short_description",
            field=models.TextField(blank=True, verbose_name="Короткое описание"),
        ),
    ]
