# Generated by Django 5.2.3 on 2026-05-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0009_alter_place_long_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Картинка"),
        ),
    ]
